// <auto-generated />
using System;
using ExpensesTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    [Migration("20260203191251_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpensesTracker.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000m,
                            Category = "Salary",
                            Date = new DateTime(2026, 2, 3, 21, 12, 50, 491, DateTimeKind.Local).AddTicks(8925),
                            Description = "Salary",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100m,
                            Category = "Groceries",
                            Date = new DateTime(2026, 2, 3, 21, 12, 50, 491, DateTimeKind.Local).AddTicks(8977),
                            Description = "Groceries",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 200m,
                            Category = "Entertainment",
                            Date = new DateTime(2026, 2, 3, 21, 12, 50, 491, DateTimeKind.Local).AddTicks(8983),
                            Description = "Cinema",
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
