// <auto-generated />
using System;
using ExpensesTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    partial class ExpenseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpensesTracker.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000m,
                            Category = "Salary",
                            Date = new DateTime(2026, 2, 3, 21, 19, 4, 311, DateTimeKind.Local).AddTicks(6304),
                            Description = "Salary",
                            Type = "INCOME"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100m,
                            Category = "Groceries",
                            Date = new DateTime(2026, 2, 3, 21, 19, 4, 311, DateTimeKind.Local).AddTicks(6356),
                            Description = "Groceries",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 200m,
                            Category = "Entertainment",
                            Date = new DateTime(2026, 2, 3, 21, 19, 4, 311, DateTimeKind.Local).AddTicks(6359),
                            Description = "Cinema",
                            Type = "EXPENSE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
